name: Merge stable into child branches

on:
  push:
    branches: ["stable"]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all branches and their history

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge changes
        run: |
          git checkout minor-next
          git merge stable

      - name: Create Pull Request for branch 'minor-next'
        id: minor-next
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.AUTO_MERGE_TOKEN }}
          branch: merge/stable-into-minor-next
          base: minor-next
          title: Merge branch 'stable' into minor-next
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          body:
