name: Merge stable into child branches

on:
  push:
    branches: ["stable"]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Reset the default branch with upstream changes
        run: |
          git checkout minor-next
          git merge stable

      - name: Create Pull Request for branch 'minor-next'
        id: minor-next
        uses: peter-evans/create-pull-request@v6
        with:
          base: minor-next
          title: Merge branch 'stable' into minor-next
