name: Merge stable into child branches

on:
  push:
    branches: ["stable"]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [minor-next, major-next]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all branches and their history

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge changes
        run: |
          git checkout ${{ matrix.branch }}
          git merge stable

      - name: Create Pull Request for branch '${{ matrix.branch }}'
        id: create-pull-request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.AUTO_MERGE_TOKEN }}
          branch: merge/stable-into-${{ matrix.branch }}
          base: ${{ matrix.branch }}
          title: Merge branch 'stable' into ${{ matrix.branch }}
          body: |
            This is an automated pull request to merge changes from 'stable' into '${{ matrix.branch }}'.
